version: '3.4'

services:
  app:
    volumes:
      - ${BASE_PATH:?Defina o path}/siga/:${BASE_PATH}/siga
      - ${BASE_PATH}/sigaex/:${BASE_PATH}/sigaex
      - ${BASE_PATH}/sigawf/:${BASE_PATH}/sigawf
      - ${BASE_PATH}/sigagc/:${BASE_PATH}/sigagc
    deploy:
      labels:
        - "traefik.tcp.routers.manager.entrypoints=dev"
        - "traefik.tcp.routers.manager.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.manager.service=manager"
        - "traefik.tcp.services.manager.loadbalancer.server.port=9990"
        - "traefik.tcp.routers.debug.entrypoints=debug"
        - "traefik.tcp.routers.debug.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.debug.service=debug"
        - "traefik.tcp.services.debug.loadbalancer.server.port=8787"
